RelationShipsExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RelationShipsExample.Models;

namespace RelationShipsExample.Controllers
{
    public class HomeController : Controller
    {
        private SmartCinetEntities db = new SmartCinetEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpPost]
        public JsonResult GetLastMovie()
        {
            var jsonResult = db.Movie.Select(m => m.Name).Take(5).ToList();

            return Json(jsonResult, JsonRequestBehavior.DenyGet);
        }
        [HttpPost]
        public JsonResult GetLastSchelude()
        {
            var jsonResult = db.Schelude.Select(s => s.Day.Days).Take(5).ToList();
            return Json(jsonResult, JsonRequestBehavior.DenyGet);
        }
        //[HttpPost]
        //public JsonResult GetLastRecent()
        //{
        //    var jsonResult = db.Schelude.Select(s => s.Day).Take(5).Last().ToList();
        //    return Json(jsonResult, JsonRequestBehavior.DenyGet);
        //}
    }
}

RelationShipsExample/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RelationShipsExample.Models;

namespace RelationShipsExample.Controllers
{
    public class MoviesController : Controller
    {
        private SmartCinetEntities db = new SmartCinetEntities();

        // GET: Movies
        public ActionResult Index()
        {
            var movie = db.Movie.Include(m => m.Classification).Include(m => m.Genre).Include(m => m.Studio);
            return View(movie.ToList());
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movie.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            ViewBag.Classification_ClassificationId = new SelectList(db.Classification, "ClassificationId", "Audience");
            ViewBag.Genre_GenreId = new SelectList(db.Genre, "GenreId", "Type");
            ViewBag.Studio_StudioId = new SelectList(db.Studio, "StudioId", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieId,Name,Year,Time,Status,Classification_ClassificationId,Genre_GenreId,Studio_StudioId")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movie.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Classification_ClassificationId = new SelectList(db.Classification, "ClassificationId", "Audience", movie.Classification_ClassificationId);
            ViewBag.Genre_GenreId = new SelectList(db.Genre, "GenreId", "Type", movie.Genre_GenreId);
            ViewBag.Studio_StudioId = new SelectList(db.Studio, "StudioId", "Name", movie.Studio_StudioId);
            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movie.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            ViewBag.Classification_ClassificationId = new SelectList(db.Classification, "ClassificationId", "Audience", movie.Classification_ClassificationId);
            ViewBag.Genre_GenreId = new SelectList(db.Genre, "GenreId", "Type", movie.Genre_GenreId);
            ViewBag.Studio_StudioId = new SelectList(db.Studio, "StudioId", "Name", movie.Studio_StudioId);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MovieId,Name,Year,Time,Status,Classification_ClassificationId,Genre_GenreId,Studio_StudioId")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Classification_ClassificationId = new SelectList(db.Classification, "ClassificationId", "Audience", movie.Classification_ClassificationId);
            ViewBag.Genre_GenreId = new SelectList(db.Genre, "GenreId", "Type", movie.Genre_GenreId);
            ViewBag.Studio_StudioId = new SelectList(db.Studio, "StudioId", "Name", movie.Studio_StudioId);
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movie.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movie.Find(id);
            db.Movie.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RelationShipsExample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RelationShipsExample/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RelationShipsExample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="col-md-12">
    <h1 class="text-center">SmartCine</h1>
    <img class="img-thumbnail align-img warning" src="/img/cine-main.jpg" alt="SmartCine App, Dominican Republic" />
</div>

<div class="row">
    <div class="col-md-4">
        <h2> Ver programaciones </h2>
        <table id="movie" class="table table-bordered">
            <tr>
                <td><b>Pelicula agregadas recientemente</b></td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </table>
        <p>@Html.ActionLink("Ver más", "Index", "Movies", null, new { @class = "btn btn-default"})</p>
    </div>
    <div class="col-md-4">
        <h2>Ver peliculas</h2>
        <p>
            <table id="content-data1">

            </table>
        </p>
        <p><a class="btn btn-default" href="#">Ver más</a></p>
    </div>
    <div class="col-md-4">
        <h2>Ver cartelera</h2>
        <p>
            <table id="content-data2"></table>
        </p>
        <p><a class="btn btn-default" href="#">Ver más</a></p>
    </div>
</div>